[package]
name = "minigrep"
description = "A grep like command written in Rust"
version = "0.1.0"
authors = ["Oliver Koch <github@oltoko.de>"]
edition = "2018"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
